id: PA5C0F5C9
initial_creation_type: ocr
source_metadata:
  volumes:
    6d10c56e316a41b0bef075f95ccc5eeb:
      base_file: v056.txt
      image_group_id: I1PD95901
      title: བཅོམ་ལྡན་འདས་མ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྙིང་པོའི་འགྲེལ་པ་དོན་གྱི་སྒྲོན་མ།
      total_pages: 1682
      volume_number: 56
